.Dd Mon Feb 10 2003               \" DATE 
.Dt APPSWITCH 1 LOCAL      \" Program name and manual section number 
.Os appswitch 1.0b1
.Sh NAME
.Nm appswitch
.Nd switch, hide, show, kill or list Mac OS X applications
.Sh SYNOPSIS
.Nm appswitch
.Op Fl sShHkFlP          \" [-sShHkFlP]
.Op Fl c Ar creator      \" [-c creator]
.Op Fl i Ar bundleID     \" [-i bundleID]
.Op Fl a Ar name         \" [-a name]
.Op Fl p Ar pid          \" [-p pid]
.Op Ar path              \" [path]
.Sh DESCRIPTION
.Nm
controls the ordering and visibility of Mac OS X application windows.
.Nm
can also list or kill running applications.
.Ss Matching options
Matching identifies one or more applications to manipulate.
.Bl -tag -width -indent
.It Fl c Ar creator
Match by creator (a four-character code, also known as a signature).
.It Fl i Ar bundle ID
Match by bundle identifier, usually consisting of the reversed dot
(.)-separated components of the application developer's Internet domain
name, followed by the application name.  For example, the Finder's
bundle identifier is
.Ar com.apple.Finder .
Bundle identifiers are not case-sensitive.
.It Fl p Ar pid
Match by process identifier, a positive number.
.It Ar path
Match by bundle path.  For packaged applications, this is the package
directory whose name typically has the .app extension, for example
.Ar /Applications/TextEdit.app
for the default installation location of TextEdit.  For non-packaged
applications, this is the path to the executable itself.
.El
.Ss Application actions
These actions apply to the matched application. If multiple
applications match the supplied criteria, only the first matching
application is acted upon.  The list option
.Fl l
displays all matching applications.
.Bl -tag -width -indent
.It Fl s
Show the application, making the application's windows frontmost. Do
not switch to the application.
.It Fl h
Hide the application's windows.
.It Fl k
Kill (force quit) the application.
.It Fl l
List applications in a format similar to that of
.Xr ps 1 . The columns of the listing are as follows:
.Bl -tag -width indent
.It PSN
The process serial number of the application.  Process serial numbers
are unique identifiers among both native Mac OS X and Classic
applications.
.It PID
The process identifier, a positive number which uniquely identifies
native Mac OS X processes, usable with the
.Fl p
matching option.  Because all Classic applications run inside
TruBlueEnvironment, a single Mac OS X process, their process
identifiers appear as -1.
.It TYPE
The four-character code identifying the application's type,
usually 'APPL' for most applications or 'FNDR' for the Finder.
Classic applications include additional types such as 'appe'
and 'APPC' for applications which perform the functions of extensions
and control panels, respectively.
.It CREA
The four-character code identifying the application's creator, usable with the
.Fl c
matching option. Some Mac OS X applications have no creator, appearing
as '????'; for these applications you must use the bundle identifier,
name or path as match criteria.
.It NAME
The user-visible application name, usable with the
.Fl a
matching option. This field is truncated to 20 characters; the
remainder of longer application names is not displayed.
.It PATH
The path to the application bundle, usable with the
.Ar path
matching option. This field is truncated to the window width, or to 80
characters if the window width cannot be determined.
.El
.It Fl p
Print the application's process identifier (PID), a positive number
and unique identifier for all applications except Classic
applications.
.El
.Ss Actions
These actions affect all applications currently running.
.Bl -tag -width -indent
.It Fl S
Show all applications, layering the windows of initially hidden
applications on top.
.It Fl H
Hide windows of all applications other than the matched application,
or the frontmost application if no application has been matched.
.It Fl F
Order the current application's windows to the front.
.El
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr open 1 ,
.Xr launch 1 ,
.Xr ps 1 ,
.Xr kill 1 ,
.Xr GetFileInfo 1
.Sh BUGS              \" Document known, unremedied bugs
The
.Fl F
option may be unreliable if issued immediately after another show or
hide command; try inserting a
.Xr sleep 1
command before it.
.Sh AUTHORS
.An "Nicholas Riley" Aq appswitch@sabi.net
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner 

